image: node:8.15.0-jessie

before_script:
  - rm -rf yarn.lock
  - rm -rf node_modules/
  - npm install

pages:
  stage: deploy
  script:
  - npm run docs
  - npm run docs_dash
  artifacts:
    paths:
    - public
  only:
  - master
